import { CalendarDays, FileStack, HandPlatter, HeartX, Home, MessageSquareReply, MessagesSquare, UserShield } from "lucide-react";
import { ApplicationType, MenuLinkType, StatCardType } from "./types";

export const Menu: MenuLinkType[] = [
    { name: 'dashboard', icon: Home, href: '/' },
    { name: 'applications', icon: FileStack, href: '/applications' },
    { name: 'calendar', icon: CalendarDays, href: '/calendar' },
    { name: 'profile', icon: UserShield, href: '/profile' }
]

export const StatCards: StatCardType[] = [
    { name: 'applications', icon: FileStack },
    { name: 'responses', icon: MessageSquareReply },
    { name: 'interviews', icon: MessagesSquare },
    { name: 'offers', icon: HandPlatter },
    { name: 'rejected', icon: HeartX }
]

export const applicationData: ApplicationType[] = [
    {
        id: 'job-001',
        org: 'TCS',
        role: 'Frontend Developer',
        location: 'Mumbai',
        type: 'Full-time',
        salary: '₹8–12 LPA',
        status: 'Applied',
        appliedDate: '2026-08-28',
        domain: 'tcs.com',
    },
    {
        id: 'job-002',
        org: 'Infosys',
        role: 'React Developer',
        location: 'Pune',
        type: 'Full-time',
        salary: '₹7–11 LPA',
        status: 'Interview',
        appliedDate: '2026-08-26',
        domain: 'infosys.com',
    },
    {
        id: 'job-003',
        org: 'Razorpay',
        role: 'Frontend Engineer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹12–18 LPA',
        status: 'Applied',
        appliedDate: '2026-08-25',
        domain: 'razorpay.com',
    },
    {
        id: 'job-004',
        org: 'Swiggy',
        role: 'Software Engineer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹14–20 LPA',
        status: 'Shortlisted',
        appliedDate: '2026-08-23',
        domain: 'swiggy.com',
    },
    {
        id: 'job-005',
        org: 'Zomato',
        role: 'React Developer',
        location: 'Gurgaon',
        type: 'Full-time',
        salary: '₹10–15 LPA',
        status: 'Applied',
        appliedDate: '2026-08-21',
        domain: 'zomato.com',
    },
    {
        id: 'job-006',
        org: 'PhonePe',
        role: 'Frontend Engineer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹15–22 LPA',
        status: 'Interview',
        appliedDate: '2026-08-20',
        domain: 'phonepe.com',
    },
    {
        id: 'job-007',
        org: 'Flipkart',
        role: 'UI Engineer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹12–18 LPA',
        status: 'Rejected',
        appliedDate: '2026-08-18',
        domain: 'flipkart.com',
    },
    {
        id: 'job-008',
        org: 'CRED',
        role: 'Frontend Developer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹14–20 LPA',
        status: 'Applied',
        appliedDate: '2026-08-16',
        domain: 'cred.club',
    },
    {
        id: 'job-009',
        org: 'Meesho',
        role: 'Software Engineer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹11–17 LPA',
        status: 'Shortlisted',
        appliedDate: '2026-08-15',
        domain: 'meesho.com',
    },
    {
        id: 'job-010',
        org: 'Freshworks',
        role: 'Frontend Engineer',
        location: 'Chennai',
        type: 'Full-time',
        salary: '₹10–16 LPA',
        status: 'Applied',
        appliedDate: '2026-08-13',
        domain: 'freshworks.com',
    },
    {
        id: 'job-011',
        org: 'Zoho',
        role: 'Web Developer',
        location: 'Chennai',
        type: 'Full-time',
        salary: '₹7–12 LPA',
        status: 'Rejected',
        appliedDate: '2026-08-11',
        domain: 'zoho.com',
    },
    {
        id: 'job-012',
        org: 'Groww',
        role: 'Frontend Developer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹12–18 LPA',
        status: 'Interview',
        appliedDate: '2026-08-09',
        domain: 'groww.in',
    },
    {
        id: 'job-013',
        org: 'Dream11',
        role: 'React Developer',
        location: 'Mumbai',
        type: 'Full-time',
        salary: '₹13–19 LPA',
        status: 'Applied',
        appliedDate: '2026-08-07',
        domain: 'dream11.com',
    },
    {
        id: 'job-014',
        org: 'Paytm',
        role: 'Software Engineer',
        location: 'Noida',
        type: 'Full-time',
        salary: '₹9–15 LPA',
        status: 'Shortlisted',
        appliedDate: '2026-08-05',
        domain: 'paytm.com',
    },
    {
        id: 'job-015',
        org: 'Myntra',
        role: 'Frontend Engineer',
        location: 'Bangalore',
        type: 'Full-time',
        salary: '₹12–18 LPA',
        status: 'Applied',
        appliedDate: '2026-08-03',
        domain: 'myntra.com',
    },
]

export const PillNames: string[] = ['all', 'applied', 'interview', 'offer', 'rejected']